name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Dar permissão ao gradlew
      run: chmod +x ./gradlew

    - name: Build do projeto
      run: ./gradlew build

    - name: Rodar os testes
      run: ./gradlew test

  release:
    name: Gerar APK após merge na main
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Dar permissão ao gradlew
      run: chmod +x ./gradlew

    - name: Build APK release
      run: ./gradlew assembleRelease

    - name: Salvar APK como artefato
      uses: actions/upload-artifact@v3
      with:
        name: smartponto-apk
        path: app/build/outputs/apk/release/app-release.apk
