name: Publicar APK

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Release com APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Dar permissão ao gradlew
      run: chmod +x ./gradlew

    - name: Build APK release
      run: ./gradlew assembleRelease

    - name: Criar release e anexar APK
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
